### ISSUE TITLE
commit-github3.py: AttributeError: 'NoneType' object has no attribute 'login'

### ISSUE THREAD

**Issue by Balive13** [arifn/github-repo-scraper#1]
Hi Arif, I ran commit-github3.py file and It shows below error.

```
Traceback (most recent call last):
  File "/Users/ali/Downloads/github-repo-scraper-master/commit-github3.py", line 104, in <module>
    process(url, start_date)
  File "/Users/ali/Downloads/github-repo-scraper-master/commit-github3.py", line 64, in process
    author = commit.author.login
AttributeError: 'NoneType' object has no attribute 'login'
```
How to I solve this error?

**Comment by arifn** [comment]
My apologies, I just noticed that you submitted an issue. You can add an exception handler to catch the NoneType error.
Have you solved this problem?
